[font]
size = 16

[font.bold]
family = "TX-02"
style = "Bold"

[font.bold_italic]
family = "TX-02"
style = "Bold Italic"

[font.italic]
family = "TX-02"
style = "Italic"

[font.normal]
family = "TX-02"
style = "Medium"

[font.offset]
y = 5

[window]
opacity = 1.0

[window.padding]
x = 8
y = 8
