[font]
size = 14

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.offset]
y = 5

[window]
opacity = 1.0

[window.padding]
x = 8
y = 8

[shell]
program = "tmux"