window:
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  dynamic_padding: false
font:
  normal:
    family: JetBrainsMono Nerd Font
  size: 22.0
  bold:
    style: Bold
  italic:
    style: Italic
# Colors (iTerm 2 default theme)
      # Colors (iTerm 2 default theme)
# Colors (iTerm 2 default theme)
# Colors (Challenger Deep)
colors:
  # Default colors
  primary:
    background: '0x1e1c31'
    foreground: '0xcbe1e7'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xff271d'
    cursor: '0xfbfcfc'
  # Normal colors
  normal:
    black:   '0x141228'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'
  # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'

background_opacity: 1
key_bindings:
  # mapping Ctrl Shift H and Ctrl Shift L so that I can use them in neovim
  - { key: H, mods: Control|Shift, chars: "\x1b[72;5u"}
  - { key: L, mods: Control|Shift, chars: "\x1b[76;5u"}
env:
  TERM: xterm-256color
