window:
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  dynamic_padding: false
font:
  normal:
    family: JetBrainsMono Nerd Font
  size: 20.0
  bold:
    style: Bold
  italic:
    style: Italic
colors:
  primary:
    background: "0x22212c"
    foreground: "0xf8f8f2"
  cursor:
    text: "0x454158"
    cursor: "0xf8f8f2"
  selection:
    text: "0xf8f8f2"
    background: "0x454158"
  normal:
    black: "0x22212c"
    red: "0xff9580"
    green: "0x8aff80"
    yellow: "0xffff80"
    blue: "0x9580ff"
    magenta: "0xff80bf"
    cyan: "0x80ffea"
    white: "0xf8f8f2"

  # Bright colors
  bright:
    black: "0x22212c"
    red: "0xffaa99"
    green: "0xa2ff99"
    yellow: "0xffff99"
    blue: "0xaa99ff"
    magenta: "0xff99cc"
    cyan: "0x99ffee"
    white: "0xffffff"
background_opacity: 1.0
