#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod4

# For now, position everything according to the window tree
bspc rule -a Anki state=floating
bspc rule -a Firefox desktop='II'
bspc rule -a * state=tiled
# bpsc rule -a * split_dir=$BSPWM_SPLIT_AREA_DIR

# Initializing alttab window switcher
alttab -w 1 -d 1 -sc 1 -mk Super_L -bk Shift_L &
