-- ideas for this plugin:
-- 1. project detection: based on lsp or patterns given by the user?
-- 2. project types: based on patterns given by the user. allow configuration per project type.
-- 3. maintain list of active projects.
-- 4. maintain sessions on each projects.
